/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pointers_BytePointers */

#ifndef _Included_Pointers_BytePointers
#define _Included_Pointers_BytePointers
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Pointers_BytePointers
 * Method:    GetValuePtr
 * Signature: (II)B
 */
JNIEXPORT jbyte JNICALL Java_Pointers_BytePointers_GetValuePtr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Pointers_BytePointers
 * Method:    SetValuePtr
 * Signature: (IIB)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_BytePointers_SetValuePtr
  (JNIEnv *, jobject, jint, jint, jbyte);

#ifdef __cplusplus
}
#endif
#endif
