/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pointers_CharPointers */

#ifndef _Included_Pointers_CharPointers
#define _Included_Pointers_CharPointers
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Pointers_CharPointers
 * Method:    GetValuePtr
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_Pointers_CharPointers_GetValuePtr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Pointers_CharPointers
 * Method:    SetValuePtr
 * Signature: (IIC)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_CharPointers_SetValuePtr
  (JNIEnv *, jobject, jint, jint, jchar);

#ifdef __cplusplus
}
#endif
#endif
