/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pointers_DPCUTIL */

#ifndef _Included_Pointers_DPCUTIL
#define _Included_Pointers_DPCUTIL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Pointers_DPCUTIL
 * Method:    DpcInitN
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_DPCUTIL_DpcInitN
  (JNIEnv *, jobject, jint);

/*
 * Class:     Pointers_DPCUTIL
 * Method:    DpcTermN
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Pointers_DPCUTIL_DpcTermN
  (JNIEnv *, jobject);

/*
 * Class:     Pointers_DPCUTIL
 * Method:    DvmgStartConfigureDevicesN
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Pointers_DPCUTIL_DvmgStartConfigureDevicesN
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Pointers_DPCUTIL
 * Method:    DvmgGetDevCountN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Pointers_DPCUTIL_DvmgGetDevCountN
  (JNIEnv *, jobject, jint);

/*
 * Class:     Pointers_DPCUTIL
 * Method:    DpcGetDpcVersionN
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_DPCUTIL_DpcGetDpcVersionN
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Pointers_DPCUTIL
 * Method:    DvmgGetDevNameN
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_DPCUTIL_DvmgGetDevNameN
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     Pointers_DPCUTIL
 * Method:    DpcOpenDataN
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_DPCUTIL_DpcOpenDataN
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     Pointers_DPCUTIL
 * Method:    DpcCloseDataN
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_DPCUTIL_DpcCloseDataN
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Pointers_DPCUTIL
 * Method:    DpcPutRegN
 * Signature: (IIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_DPCUTIL_DpcPutRegN
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     Pointers_DPCUTIL
 * Method:    DpcGetRegN
 * Signature: (IIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_DPCUTIL_DpcGetRegN
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     Pointers_DPCUTIL
 * Method:    DpcPutRegSetN
 * Signature: (IIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_DPCUTIL_DpcPutRegSetN
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     Pointers_DPCUTIL
 * Method:    DpcGetRegSetN
 * Signature: (IIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_DPCUTIL_DpcGetRegSetN
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     Pointers_DPCUTIL
 * Method:    DpcPutRegRepeatN
 * Signature: (IIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_DPCUTIL_DpcPutRegRepeatN
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     Pointers_DPCUTIL
 * Method:    DpcGetRegRepeatN
 * Signature: (IIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_DPCUTIL_DpcGetRegRepeatN
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
