/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pointers_IntPointers */

#ifndef _Included_Pointers_IntPointers
#define _Included_Pointers_IntPointers
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Pointers_IntPointers
 * Method:    GetValuePtr
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Pointers_IntPointers_GetValuePtr
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Pointers_IntPointers
 * Method:    SetValuePtr
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_IntPointers_SetValuePtr
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
