/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pointers_PTRFUNCT */

#ifndef _Included_Pointers_PTRFUNCT
#define _Included_Pointers_PTRFUNCT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Pointers_PTRFUNCT
 * Method:    MallocPtr
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Pointers_PTRFUNCT_MallocPtr
  (JNIEnv *, jclass, jint);

/*
 * Class:     Pointers_PTRFUNCT
 * Method:    FreePtr
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_PTRFUNCT_FreePtr
  (JNIEnv *, jclass, jint);

/*
 * Class:     Pointers_PTRFUNCT
 * Method:    LoadLibraryDLLN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Pointers_PTRFUNCT_LoadLibraryDLLN
  (JNIEnv *, jclass, jint);

/*
 * Class:     Pointers_PTRFUNCT
 * Method:    FreeLibraryN
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_PTRFUNCT_FreeLibraryN
  (JNIEnv *, jclass, jint);

/*
 * Class:     Pointers_PTRFUNCT
 * Method:    FindWindowAN
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Pointers_PTRFUNCT_FindWindowAN
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Pointers_PTRFUNCT
 * Method:    GetActiveWindowN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Pointers_PTRFUNCT_GetActiveWindowN
  (JNIEnv *, jclass);

/*
 * Class:     Pointers_PTRFUNCT
 * Method:    ShowWindowN
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_PTRFUNCT_ShowWindowN
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Pointers_PTRFUNCT
 * Method:    GetAncestorN
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Pointers_PTRFUNCT_GetAncestorN
  (JNIEnv *, jclass, jint);

/*
 * Class:     Pointers_PTRFUNCT
 * Method:    OpenFileDialogN
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_Pointers_PTRFUNCT_OpenFileDialogN
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     Pointers_PTRFUNCT
 * Method:    SetIconN
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_Pointers_PTRFUNCT_SetIconN
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Pointers_PTRFUNCT
 * Method:    PruebasN
 * Signature: (I[C)V
 */
JNIEXPORT void JNICALL Java_Pointers_PTRFUNCT_PruebasN
  (JNIEnv *, jclass, jint, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
